### PR TITLE
Skip invisible layers

### PR DESCRIPTION
**Pull request by lynnerang**
Adds new flag to skip invisible layers when running Figma's traversal methods like `findAll`, for both Specter 1.0 and 2.0.

### CODE REVIEW

**Review by gblakeman — APPROVED** [review]
🌈🦄

**Review by joeyyang — APPROVED** [review]
Whee!

**Comment by gblakeman** [comment]
@lynnerang I didn’t catch this in my review, but `@figma/plugin-typings` needs to be updated in `package.json`, otherwise on a fresh install npm uses an old version that does not have `skipInvisibleInstanceChildren`.

**Comment by lynnerang** [comment]
> @lynnerang I didn’t catch this in my review, but `@figma/plugin-typings` needs to be updated in `package.json`, otherwise on a fresh install npm uses an old version that does not have `skipInvisibleInstanceChildren`.

yes, thank you for checking!  I updated it, but not sure why it's only showing package-lock in the diff.  just re-opened the branch and tried updating it again, and still no change in version num.  maybe I accidentally merged that bit in my previous PR?

**Comment by gblakeman** [comment]
It’s counterintuitive, but to change `package.json` requirements I believe you have to [always do an](https://docs.npmjs.com/updating-packages-downloaded-from-the-registry) `install`, not `update`. The `update` command just bumps them as far as possible within the requirements set out in `package.json`. 🙃

**Comment by lynnerang** [comment]
Oh no way, I never noticed that! dang, thanks for the critical pro tip...I'll do that then 😆

**Comment by gblakeman** [comment]
I put the wrong link in that comment. Better explanation [here](https://www.educative.io/edpresso/how-to-update-packagejson), if curious.

**Pull request merged**
